-- ============================================================
-- plugins/spell.lua — Built-in spell checking
--
-- Uses Neovim's built-in spell engine (no plugin required).
-- Off by default in code files; auto-enabled for prose.
-- When enabled in a code file with syntax/treesitter active,
-- Neovim automatically limits spell checking to comment and
-- string regions — identifiers and keywords are never flagged.
--
-- Keymaps (built-in, always active when spell is on):
--   ]s          — jump to next misspelled word
--   [s          — jump to previous misspelled word
--   z=          — show correction suggestions for word under cursor
--   zg          — add word to personal dictionary
--   zw          — mark word as wrong
--   zug / zuw   — undo zg / zw
--
-- Keymaps (defined here):
--   <leader>ts  — toggle spell on/off in current buffer
--   <leader>tL  — pick spell language from a list (Telescope picker)
--
-- Personal dictionaries (per language, version-controlled):
--   spell/en_us.utf-8.add, spell/fr.utf-8.add, etc.
--   Compiled .spl binaries are gitignored (auto-generated by Neovim).
--
-- LAZY: No — options and autocmds registered at startup.
-- ============================================================

local spell_dir = vim.fn.stdpath('config') .. '/spell/'

-- Default: US English.
vim.o.spelllang = 'en_us'
vim.o.spellfile = spell_dir .. 'en_us.utf-8.add'

-- Off by default; auto-enabled for prose filetypes below.
vim.o.spell = false

-- Supported languages shown in the picker.
-- Neovim downloads the spell file for each language automatically on first use.
local languages = {
  { label = 'English (US)',   code = 'en_us' },
  { label = 'English (UK)',   code = 'en_gb' },
  { label = 'French',         code = 'fr'    },
  { label = 'German',         code = 'de'    },
  { label = 'Spanish',        code = 'es'    },
  { label = 'Italian',        code = 'it'    },
  { label = 'Portuguese',     code = 'pt'    },
  { label = 'Dutch',          code = 'nl'    },
  { label = 'Russian',        code = 'ru'    },
}

-- Auto-enable for prose filetypes where spell is always useful.
vim.api.nvim_create_autocmd('FileType', {
  group    = vim.api.nvim_create_augroup('spell-prose', { clear = true }),
  pattern  = { 'markdown', 'gitcommit', 'text', 'rst', 'mail' },
  callback = function() vim.opt_local.spell = true end,
})

-- <leader>ts: toggle spell on/off in the current buffer.
vim.keymap.set('n', '<leader>ts', function()
  vim.opt_local.spell = not vim.opt_local.spell:get()
  vim.notify('Spell check ' .. (vim.opt_local.spell:get() and 'on' or 'off'),
    vim.log.levels.INFO)
end, { desc = 'Toggle spell check' })

-- <leader>tL: pick spell language via vim.ui.select (Telescope picker).
-- Switches spelllang and spellfile in the current buffer; enables spell if
-- it was off. Personal word lists are kept per language so zg words don't
-- bleed across languages.
vim.keymap.set('n', '<leader>tL', function()
  vim.ui.select(languages, {
    prompt = 'Spell language',
    format_item = function(item)
      local current = vim.opt_local.spelllang:get()[1] or vim.o.spelllang
      return item.label .. (item.code == current and '  ✓' or '')
    end,
  }, function(choice)
    if not choice then return end
    vim.opt_local.spelllang = choice.code
    vim.opt_local.spellfile = spell_dir .. choice.code .. '.utf-8.add'
    if not vim.opt_local.spell:get() then
      vim.opt_local.spell = true
    end
    vim.notify('Spell language: ' .. choice.label, vim.log.levels.INFO)
  end)
end, { desc = 'Pick spell check language' })
